input {
  beats {
    port => 5044
  }
}

filter {
  if [fields][service] == "nginx" {
    grok {
      match => {
        "message" => '%{IPORHOST:remote_ip} - %{DATA:user} \[%{HTTPDATE:access_time}\] "%{WORD:http_method} %{DATA:url} HTTP/%{NUMBER:http_version}" %{NUMBER:response_code} %{NUMBER:body_sent_bytes} "%{DATA:referrer}" "%{DATA:agent}"'
      }
    }
    mutate {
      convert => { "response_code" => "integer" }
      convert => { "body_sent_bytes" => "integer" }
    }
  }
}

output {
  elasticsearch {
    hosts    => ["${ELASTIC_HOSTS}"]
    user     => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
    cacert => "/usr/share/logstash/certs/ca/ca.crt"
    index    => "nginx-logs-%{+YYYY.MM.dd}"
  }
}
