---
- name: Create nginx_exporter user
  ansible.builtin.user:
    name: nginx_exporter
    shell: /usr/sbin/nologin
    system: true
    create_home: false
- name: Download nginx_exporter
  ansible.builtin.get_url:
    url: https://github.com/nginx/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version }}/nginx-prometheus-exporter_{{ nginx_exporter_version }}_linux_amd64.tar.gz
    dest: /tmp/nginx_exporter.tar.gz
- name: Extract nginx_exporter
  ansible.builtin.unarchive:
    src: /tmp/nginx_exporter.tar.gz
    dest: /tmp/
    remote_src: true
- name: Copy binary nginx_exporter
  ansible.builtin.copy:
    src: /tmp/nginx-prometheus-exporter
    dest: /usr/local/bin/nginx-prometheus-exporter
    mode: "0755"
    remote_src: true
  notify: Restart nginx_exporter
- name: Create systemd unit for nginx_exporter
  ansible.builtin.template:
    src: nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
  notify: Restart nginx_exporter
- name: Start nginx_exporter service
  ansible.builtin.service:
    name: nginx_exporter
    state: started
    enabled: true
    daemon_reload: true
