---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
- name: Generate nginx config
  ansible.builtin.template:
    src: load-balancer.conf.j2
    dest: /etc/nginx/sites-available/load-balancer.conf
  notify: Restart nginx
- name: Enable nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/load-balancer.conf
    dest: /etc/nginx/sites-enabled/load-balancer.conf
    state: link
  notify: Restart nginx
- name: Delete default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx
- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
